default: 
	g++ -g -std=c++17 -fsanitize=address -Wall -pthread test.cpp task.cpp manager.cpp 
	./a.out	
	# rm a.out
test1:
	g++ -g -std=c++17 -fsanitize=address -Wall -pthread test.cpp task.cpp manager.cpp 
	./a.out	
test2:
	g++ -g -std=c++17 -fsanitize=address -Wall -pthread test2.cpp task.cpp manager.cpp 
	./a.out	